# Test prompts for inference

test_prompts = [
    # Basic colors
    "red",
    "orange",
    "yellow",
    "green",
    "blue",
    "indigo",
    "violet",
    "pink",
    "brown",
    "black",
    "white",
    "gray",
    # Colors with adjectives
    "deep red",
    "pale pink",
    "dusty rose",
    "muted teal",
    "vibrant lime",
    "neon magenta",
    "pastel lavender",
    "charcoal gray",
    "sunny yellow",
    "burnt sienna",
    # Objects with a single color theme
    "avocado",
    "banana",
    "blueberry",
    "olive",
    "pomegranate",
    "matcha",
    "wood",
    "water",
    "topaz",
    # Objects with color combinations
    "pizza",
    "burger",
    "cupcakes",
    "zebra",
    "peacock",
    "rainbow",
    "traffic light",
    # Styles
    "monochrome",
    "colorful",
    "fluorescent",
    "metallic",
    "high contrast",
    "pastel",
    "vintage",
    "modern",
    "futuristic",
    # Scenes
    "sunrise",
    "sunset",
    "midnight",
    "cityscape",
    "mountain",
    "garden",
    "spring",
    "summer",
    "autumn",
    "winter",
    # Places
    "Australia",
    "Hawaii",
    "Korea",
    "Italy",
    "Mount Fuji",
    "Himalayas",
    "Sahara",
    # Emotions and abstract concepts
    "happiness",
    "sorrow",
    "anger",
    "love",
    "fear",
    "disgust",
    "calmness",
    "emptiness",
    "chaos",
    "energy",
    "infinity",
    "hallucination",
    # Festivals and cultures
    "Christmas",
    "Halloween",
    "lion dance",
    "kimono",
    # Brands
    "Coca-Cola",
    "McDonald's",
    "Starbucks",
    "Google",
    # Compositions
    "warm and cold",
    "triadic color scheme",
    "complementary colors",
    "analogous colors",
    "roses and lilies",
    "sunflowers in a blue vase",
    "black and yellow stripes",
    "neon lights at night",
    "sheep on grassland",
    "sunlight through leaves",
    # Negations & exclusions
    "no red",
    "no red or blue",
    "rainbow without green",
]
